# Generated by Django 5.1.1 on 2025-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_number',
            field=models.CharField(blank=True, editable=False, max_length=7, unique=True),
        ),
    ]
