# Generated by Django 5.1.1 on 2025-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
